/**
 * React Admin-specific MUI component overrides.
 *
 * These overrides target CSS classes generated by React Admin's built-in
 * components (RaLayout, RaFilterForm, RaLoginForm, etc.) and should only
 * be applied in applications that use React Admin.
 *
 * React Admin registers custom component keys at runtime that TypeScript
 * doesn't know about, so we use a Record type instead of the strict
 * Components type.
 */

import type { Theme } from '@mui/material/styles';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type LooseComponents = Record<string, any>;

export const raComponentOverrides = (theme: Theme): LooseComponents => ({
  // CSS Baseline (React Admin layout adjustments)
  MuiCssBaseline: {
    styleOverrides: {
      '#main-content.RaLayout-content': {
        backgroundColor: theme.palette.background.paper,
        padding: '16px',
        borderRadius: '8px',
      },
    },
  },

  // React Admin Filter Form
  RaFilterForm: {
    styleOverrides: {
      root: {
        paddingBottom: '8px',
      },
    },
  },

  // React Admin Login Form
  RaLoginForm: {
    styleOverrides: {
      root: {
        '& .MuiFormControl-root': {
          width: '100%',
        },
      },
    },
  },

  // Scoped CSS Baseline (main content min-width fix)
  MuiScopedCssBaseline: {
    styleOverrides: {
      root: {
        '& main': {
          minWidth: 0,
        },
      },
    },
  },

  // MenuItem (increased vertical padding for touch targets)
  MuiMenuItem: {
    styleOverrides: {
      root: {
        paddingTop: '8px',
        paddingBottom: '8px',
      },
    },
  },
});
